# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-06 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('badges_app', '0002_auto_20181106_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='printer',
            name='secret_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
