# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-12 14:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mercury_app', '0001_initial'),
        ('badges_app', '0005_auto_20181108_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printer',
            name='organization',
        ),
        migrations.AddField(
            model_name='printer',
            name='event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mercury_app.Event'),
        ),
    ]
