# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-13 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges_app', '0007_auto_20181112_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='auto',
            field=models.BooleanField(default=False),
        ),
    ]
