before_script:
  - sudo /etc/init.d/postgresql stop

services:
  - docker

install:
  - docker-compose build

script:
  - docker-compose run -e TRAVIS=true -e TRAVIS_JOB_ID="$TRAVIS_JOB_ID" -e TRAVIS_BRANCH="$TRAVIS_BRANCH" -e COVERALLS_REPO_TOKEN="$repo_token" django bash -c "coverage run manage.py test && coveralls"
