language: python
python:
  - "3.6.5"

services: postgresql

env:
  global:
# - DJANGO="x.y.z"
  - DJANGO_SETTINGS_MODULE="mercury_site.settings"
  - PYTHONPATH="/home/travis/build/evbeda/mercury"
  - PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt

before_script:
  - psql -c 'create database travisdb;' -U postgres

script:
 - python manage.py migrate
