# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-06 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='key',
            field=models.CharField(default='3a5a195fab374384a8b9e3d0af8c3008', max_length=32),
        ),
        migrations.AddField(
            model_name='printer',
            name='secret_key',
            field=models.CharField(default='9b78d694d731445fa009d5d294739457', max_length=32),
        ),
    ]
