# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-08 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges_app', '0004_auto_20181108_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='secret_key',
            field=models.UUIDField(null=True, unique=True),
        ),
    ]
