# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-12 14:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('badges_app', '0006_auto_20181112_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercury_app.Event'),
        ),
    ]
