# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-15 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mercury_app', '0003_event_badges_tool_auto'),
        ('badges_app', '0008_printer_auto'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string', models.CharField(max_length=255)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercury_app.Event')),
            ],
        ),
    ]
