# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-12 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercury_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='has_merchandise',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
