# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-13 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercury_app', '0002_order_has_merchandise'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='badges_tool_auto',
            field=models.BooleanField(default=False),
        ),
    ]
