# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-23 14:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mercury_app', '0002_auto_20181016_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('eb_attendee_id', models.CharField(max_length=16)),
                ('barcode', models.CharField(max_length=30)),
                ('checked_in', models.BooleanField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercury_app.Order')),
            ],
        ),
    ]
