# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-05 17:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('eb_attendee_id', models.CharField(max_length=16)),
                ('barcode', models.CharField(max_length=30, unique=True)),
                ('barcode_url', models.CharField(max_length=120)),
                ('checked_in', models.BooleanField()),
                ('checked_in_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(blank=True, max_length=1024, null=True)),
                ('eb_event_id', models.CharField(max_length=40, unique=True)),
                ('url', models.CharField(max_length=128)),
                ('date_tz', models.CharField(max_length=64)),
                ('start_date_utc', models.DateTimeField()),
                ('end_date_utc', models.DateTimeField()),
                ('created', models.DateTimeField()),
                ('changed', models.DateTimeField()),
                ('status', models.CharField(max_length=16)),
                ('badges_tool', models.BooleanField(default=False)),
                ('merchandise_tool', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Merchandise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eb_merchandising_id', models.CharField(max_length=8, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('item_type', models.CharField(max_length=128)),
                ('currency', models.CharField(max_length=3)),
                ('quantity', models.IntegerField(default=0)),
                ('value', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('eb_order_id', models.BigIntegerField(unique=True)),
                ('changed', models.DateTimeField()),
                ('created', models.DateTimeField()),
                ('status', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=256)),
                ('merch_status', models.CharField(choices=[('CO', 'Delivered'), ('PA', 'Partially delivered'), ('PE', 'Pending delivery')], default='PE', max_length=2)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercury_app.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eb_organization_id', models.CharField(default=0, max_length=40, unique=True)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('notes', models.CharField(max_length=256)),
                ('device_name', models.CharField(max_length=128)),
                ('operation_type', models.CharField(choices=[('HA', 'Fulfillment'), ('RE', 'Return')], default='HA', max_length=2)),
                ('from_who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('merchandise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercury_app.Merchandise')),
            ],
        ),
        migrations.CreateModel(
            name='UserOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercury_app.Organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserWebhook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_id', models.CharField(max_length=16, unique=True)),
                ('wh_type', models.CharField(choices=[('CH', 'Check In'), ('OR', 'Order Placed')], max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='merchandise',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercury_app.Order'),
        ),
        migrations.AddField(
            model_name='event',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercury_app.Organization'),
        ),
        migrations.AddField(
            model_name='attendee',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercury_app.Order'),
        ),
    ]
