# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-26 16:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(blank=True, max_length=1024, null=True)),
                ('eb_event_id', models.BigIntegerField(default=0, unique=True)),
                ('url', models.CharField(max_length=128)),
                ('date_tz', models.CharField(max_length=64)),
                ('start_date_utc', models.DateTimeField()),
                ('end_date_utc', models.DateTimeField()),
                ('created', models.DateTimeField()),
                ('changed', models.DateTimeField()),
                ('status', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Merchandise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('item_type', models.CharField(max_length=128)),
                ('currency', models.CharField(max_length=16)),
                ('value', models.IntegerField()),
                ('delivered', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eb_order_id', models.BigIntegerField(default=0, unique=True)),
                ('changed', models.DateTimeField()),
                ('created', models.DateTimeField()),
                ('name', models.CharField(max_length=256)),
                ('status', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=256)),
                ('merch_status', models.CharField(choices=[('CO', 'Completed'), ('PA', 'Partial'), ('PE', 'Pending')], default='PE', max_length=2)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercury_app.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eb_organization_id', models.BigIntegerField(default=0, unique=True)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='UserOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercury_app.Organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='merchandise',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercury_app.Order'),
        ),
        migrations.AddField(
            model_name='event',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercury_app.Organization'),
        ),
    ]
