# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-16 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercury_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='merch_status',
            field=models.CharField(choices=[('CO', 'Delivered'), ('PA', 'Partially delivered'), ('PE', 'Pending delivery')], default='PE', max_length=2),
        ),
    ]
