# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-04 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercury_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='to_who',
        ),
        migrations.AddField(
            model_name='transaction',
            name='notes',
            field=models.CharField(default=0, max_length=256),
            preserve_default=False,
        ),
    ]
