# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-25 17:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mercury_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='event',
            old_name='organization_id',
            new_name='organization',
        ),
        migrations.RenameField(
            model_name='merchandise',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='event_id',
            new_name='event',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='owner',
        ),
        migrations.AddField(
            model_name='userorganization',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercury_app.Organization'),
        ),
        migrations.AddField(
            model_name='userorganization',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
