# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-27 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercury_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='eb_organization_id',
            field=models.CharField(default=0, max_length=40, unique=True),
        ),
    ]
