# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-27 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercury_app', '0002_auto_20180927_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eb_event_id',
            field=models.CharField(default=0, max_length=40, unique=True),
        ),
    ]
