# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-25 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercury_app', '0002_auto_20180925_1730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='id_order',
            new_name='eb_order_id',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='org_id',
            new_name='eb_organization_id',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_id',
        ),
        migrations.AddField(
            model_name='event',
            name='eb_event_id',
            field=models.IntegerField(default=0),
        ),
    ]
