# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-24 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercury_app', '0003_attendee'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='barcode_url',
            field=models.CharField(default=0, max_length=120),
            preserve_default=False,
        ),
    ]
