# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-04 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercury_app', '0003_auto_20181004_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eb_event_id',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='eb_merchandising_id',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='eb_order_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
