# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-28 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercury_app', '0003_auto_20180927_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchandise',
            name='value',
            field=models.CharField(max_length=16),
        ),
    ]
