# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-25 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercury_app', '0003_auto_20180925_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchandise',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='merch_status',
            field=models.CharField(choices=[('CO', 'Completed'), ('PA', 'Partial'), ('PE', 'Pending')], default='PE', max_length=2),
        ),
    ]
