# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-28 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercury_app', '0004_auto_20180928_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchandise',
            name='delivery_date',
            field=models.DateTimeField(default=None),
        ),
    ]
