# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-31 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercury_app', '0005_auto_20181025_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwebhook',
            name='wh_type',
            field=models.CharField(choices=[('CH', 'Check In'), ('OR', 'Order Placed')], default='OR', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='operation_type',
            field=models.CharField(choices=[('HA', 'Fulfillment'), ('RE', 'Return')], default='HA', max_length=2),
        ),
    ]
